extern int GLOBALMOD caxpy_(long *n,struct *ca,struct *cx,long *incx,struct *cy,long *incy); 
extern int GLOBALMOD ccopy_(long *n,struct *cx,long *incx,struct *cy,long *incy); 
extern void GLOBALMOD cdotc_(struct *ret_val,long *n,struct *cx,long *incx,struct *cy,long *incy); 
extern void GLOBALMOD cdotu_(struct *ret_val,long *n,struct *cx,long *incx,struct *cy,long *incy); 
extern int GLOBALMOD cgbmv_(char *trans,long *m,long *n,long *kl,long *ku,struct *alpha,struct *a,long *lda,struct *x,long *incx,struct *beta,struct *y,long *incy,long trans_len); 
extern int GLOBALMOD cgemm_(char *transa,char *transb,long *m,long *n,long *k,struct *alpha,struct *a,long *lda,struct *b,long *ldb,struct *beta,struct *c,long *ldc,long transa_len,long transb_len); 
extern int GLOBALMOD cgemv_(char *trans,long *m,long *n,struct *alpha,struct *a,long *lda,struct *x,long *incx,struct *beta,struct *y,long *incy,long trans_len); 
extern int GLOBALMOD cgerc_(long *m,long *n,struct *alpha,struct *x,long *incx,struct *y,long *incy,struct *a,long *lda); 
extern int GLOBALMOD cgeru_(long *m,long *n,struct *alpha,struct *x,long *incx,struct *y,long *incy,struct *a,long *lda); 
extern int GLOBALMOD chbmv_(char *uplo,long *n,long *k,struct *alpha,struct *a,long *lda,struct *x,long *incx,struct *beta,struct *y,long *incy,long uplo_len); 
extern int GLOBALMOD chemm_(char *side,char *uplo,long *m,long *n,struct *alpha,struct *a,long *lda,struct *b,long *ldb,struct *beta,struct *c,long *ldc,long side_len,long uplo_len); 
extern int GLOBALMOD chemv_(char *uplo,long *n,struct *alpha,struct *a,long *lda,struct *x,long *incx,struct *beta,struct *y,long *incy,long uplo_len); 
extern int GLOBALMOD cher_(char *uplo,long *n,float *alpha,struct *x,long *incx,struct *a,long *lda,long uplo_len); 
extern int GLOBALMOD cher2_(char *uplo,long *n,struct *alpha,struct *x,long *incx,struct *y,long *incy,struct *a,long *lda,long uplo_len); 
extern int GLOBALMOD cher2k_(char *uplo,char *trans,long *n,long *k,struct *alpha,struct *a,long *lda,struct *b,long *ldb,float *beta,struct *c,long *ldc,long uplo_len,long trans_len); 
extern int GLOBALMOD cherk_(char *uplo,char *trans,long *n,long *k,float *alpha,struct *a,long *lda,float *beta,struct *c,long *ldc,long uplo_len,long trans_len); 
extern int GLOBALMOD chpmv_(char *uplo,long *n,struct *alpha,struct *ap,struct *x,long *incx,struct *beta,struct *y,long *incy,long uplo_len); 
extern int GLOBALMOD chpr_(char *uplo,long *n,float *alpha,struct *x,long *incx,struct *ap,long uplo_len); 
extern int GLOBALMOD chpr2_(char *uplo,long *n,struct *alpha,struct *x,long *incx,struct *y,long *incy,struct *ap,long uplo_len); 
extern int GLOBALMOD crotg_(struct *ca,struct *cb,float *c,struct *s); 
extern int GLOBALMOD cscal_(long *n,struct *ca,struct *cx,long *incx); 
extern int GLOBALMOD csrot_(long *n,struct *cx,long *incx,struct *cy,long *incy,float *c,float *s); 
extern int GLOBALMOD csscal_(long *n,float *sa,struct *cx,long *incx); 
extern int GLOBALMOD cswap_(long *n,struct *cx,long *incx,struct *cy,long *incy); 
extern int GLOBALMOD csymm_(char *side,char *uplo,long *m,long *n,struct *alpha,struct *a,long *lda,struct *b,long *ldb,struct *beta,struct *c,long *ldc,long side_len,long uplo_len); 
extern int GLOBALMOD csyr2k_(char *uplo,char *trans,long *n,long *k,struct *alpha,struct *a,long *lda,struct *b,long *ldb,struct *beta,struct *c,long *ldc,long uplo_len,long trans_len); 
extern int GLOBALMOD csyrk_(char *uplo,char *trans,long *n,long *k,struct *alpha,struct *a,long *lda,struct *beta,struct *c,long *ldc,long uplo_len,long trans_len); 
extern int GLOBALMOD ctbmv_(char *uplo,char *trans,char *diag,long *n,long *k,struct *a,long *lda,struct *x,long *incx,long uplo_len,long trans_len,long diag_len); 
extern int GLOBALMOD ctbsv_(char *uplo,char *trans,char *diag,long *n,long *k,struct *a,long *lda,struct *x,long *incx,long uplo_len,long trans_len,long diag_len); 
extern int GLOBALMOD ctpmv_(char *uplo,char *trans,char *diag,long *n,struct *ap,struct *x,long *incx,long uplo_len,long trans_len,long diag_len); 
extern int GLOBALMOD ctpsv_(char *uplo,char *trans,char *diag,long *n,struct *ap,struct *x,long *incx,long uplo_len,long trans_len,long diag_len); 
extern int GLOBALMOD ctrmm_(char *side,char *uplo,char *transa,char *diag,long *m,long *n,struct *alpha,struct *a,long *lda,struct *b,long *ldb,long side_len,long uplo_len,long transa_len,long diag_len); 
extern int GLOBALMOD ctrmv_(char *uplo,char *trans,char *diag,long *n,struct *a,long *lda,struct *x,long *incx,long uplo_len,long trans_len,long diag_len); 
extern int GLOBALMOD ctrsm_(char *side,char *uplo,char *transa,char *diag,long *m,long *n,struct *alpha,struct *a,long *lda,struct *b,long *ldb,long side_len,long uplo_len,long transa_len,long diag_len); 
extern int GLOBALMOD ctrsv_(char *uplo,char *trans,char *diag,long *n,struct *a,long *lda,struct *x,long *incx,long uplo_len,long trans_len,long diag_len); 
extern double GLOBALMOD dasum_(long *n,double *dx,long *incx);
extern int GLOBALMOD daxpy_(long *n,double *da,double *dx,long *incx,double *dy,long *incy);
extern double GLOBALMOD dcabs1_(struct *z); 
extern int GLOBALMOD dcopy_(long *n,double *dx,long *incx,double *dy,long *incy);
extern double GLOBALMOD ddot_(long *n,double *dx,long *incx,double *dy,long *incy);
extern int GLOBALMOD dgbmv_(char *trans,long *m,long *n,long *kl,long *ku,double *alpha,double *a,long *lda,double *x,long *incx,double *beta,double *y,long *incy,long trans_len);
extern int GLOBALMOD dgemm_(char *transa,char *transb,long *m,long *n,long *k,double *alpha,double *a,long *lda,double *b,long *ldb,double *beta,double *c,long *ldc,long transa_len,long transb_len);
extern int GLOBALMOD dgemv_(char *trans,long *m,long *n,double *alpha,double *a,long *lda,double *x,long *incx,double *beta,double *y,long *incy,long trans_len);
extern int GLOBALMOD dger_(long *m,long *n,double *alpha,double *x,long *incx,double *y,long *incy,double *a,long *lda);
extern double GLOBALMOD dnrm2_(long *n,double *dx,long *incx);
extern int GLOBALMOD drot_(long *n,double *dx,long *incx,double *dy,long *incy,double *c,double *s);
extern int GLOBALMOD drotg_(double *da,double *db,double *c,double *s);
extern int GLOBALMOD drotm_(long *n,double *dx,long *incx,double *dy,long *incy,double *dparam);
extern int GLOBALMOD drotmg_(double *dd1,double *dd2,double *dx1,double *dy1,double *dparam);
extern int GLOBALMOD dsbmv_(char *uplo,long *n,long *k,double *alpha,double *a,long *lda,double *x,long *incx,double *beta,double *y,long *incy,long uplo_len);
extern int GLOBALMOD dscal_(long *n,double *da,double *dx,long *incx);
extern int GLOBALMOD dspmv_(char *uplo,long *n,double *alpha,double *ap,double *x,long *incx,double *beta,double *y,long *incy,long uplo_len);
extern int GLOBALMOD dspr_(char *uplo,long *n,double *alpha,double *x,long *incx,double *ap,long uplo_len);
extern int GLOBALMOD dspr2_(char *uplo,long *n,double *alpha,double *x,long *incx,double *y,long *incy,double *ap,long uplo_len);
extern int GLOBALMOD dswap_(long *n,double *dx,long *incx,double *dy,long *incy);
extern int GLOBALMOD dsymm_(char *side,char *uplo,long *m,long *n,double *alpha,double *a,long *lda,double *b,long *ldb,double *beta,double *c,long *ldc,long side_len,long uplo_len);
extern int GLOBALMOD dsymv_(char *uplo,long *n,double *alpha,double *a,long *lda,double *x,long *incx,double *beta,double *y,long *incy,long uplo_len);
extern int GLOBALMOD dsyr_(char *uplo,long *n,double *alpha,double *x,long *incx,double *a,long *lda,long uplo_len);
extern int GLOBALMOD dsyr2_(char *uplo,long *n,double *alpha,double *x,long *incx,double *y,long *incy,double *a,long *lda,long uplo_len);
extern int GLOBALMOD dsyr2k_(char *uplo,char *trans,long *n,long *k,double *alpha,double *a,long *lda,double *b,long *ldb,double *beta,double *c,long *ldc,long uplo_len,long trans_len);
extern int GLOBALMOD dsyrk_(char *uplo,char *trans,long *n,long *k,double *alpha,double *a,long *lda,double *beta,double *c,long *ldc,long uplo_len,long trans_len);
extern int GLOBALMOD dtbmv_(char *uplo,char *trans,char *diag,long *n,long *k,double *a,long *lda,double *x,long *incx,long uplo_len,long trans_len,long diag_len);
extern int GLOBALMOD dtbsv_(char *uplo,char *trans,char *diag,long *n,long *k,double *a,long *lda,double *x,long *incx,long uplo_len,long trans_len,long diag_len);
extern int GLOBALMOD dtpmv_(char *uplo,char *trans,char *diag,long *n,double *ap,double *x,long *incx,long uplo_len,long trans_len,long diag_len);
extern int GLOBALMOD dtpsv_(char *uplo,char *trans,char *diag,long *n,double *ap,double *x,long *incx,long uplo_len,long trans_len,long diag_len);
extern int GLOBALMOD dtrmm_(char *side,char *uplo,char *transa,char *diag,long *m,long *n,double *alpha,double *a,long *lda,double *b,long *ldb,long side_len,long uplo_len,long transa_len,long diag_len);
extern int GLOBALMOD dtrmv_(char *uplo,char *trans,char *diag,long *n,double *a,long *lda,double *x,long *incx,long uplo_len,long trans_len,long diag_len);
extern int GLOBALMOD dtrsm_(char *side,char *uplo,char *transa,char *diag,long *m,long *n,double *alpha,double *a,long *lda,double *b,long *ldb,long side_len,long uplo_len,long transa_len,long diag_len);
extern int GLOBALMOD dtrsv_(char *uplo,char *trans,char *diag,long *n,double *a,long *lda,double *x,long *incx,long uplo_len,long trans_len,long diag_len);
extern double GLOBALMOD dzasum_(long *n,struct *zx,long *incx); 
extern double GLOBALMOD dznrm2_(long *n,struct *zx,long *incx); 
extern long GLOBALMOD icamax_(long *n,struct *cx,long *incx); 
extern long GLOBALMOD idamax_(long *n,double *dx,long *incx);
extern long GLOBALMOD isamax_(long *n,float *sx,long *incx);
extern long GLOBALMOD izamax_(long *n,struct *zx,long *incx); 
extern long GLOBALMOD lsame_(char *ca,char *cb,long ca_len,long cb_len);
extern double GLOBALMOD sasum_(long *n,float *sx,long *incx);
extern int GLOBALMOD saxpy_(long *n,float *sa,float *sx,long *incx,float *sy,long *incy);
extern double GLOBALMOD scasum_(long *n,struct *cx,long *incx); 
extern double GLOBALMOD scnrm2_(long *n,struct *cx,long *incx); 
extern int GLOBALMOD scopy_(long *n,float *sx,long *incx,float *sy,long *incy);
extern double GLOBALMOD sdot_(long *n,float *sx,long *incx,float *sy,long *incy);
extern int GLOBALMOD sgbmv_(char *trans,long *m,long *n,long *kl,long *ku,float *alpha,float *a,long *lda,float *x,long *incx,float *beta,float *y,long *incy,long trans_len);
extern int GLOBALMOD sgemm_(char *transa,char *transb,long *m,long *n,long *k,float *alpha,float *a,long *lda,float *b,long *ldb,float *beta,float *c,long *ldc,long transa_len,long transb_len);
extern int GLOBALMOD sgemv_(char *trans,long *m,long *n,float *alpha,float *a,long *lda,float *x,long *incx,float *beta,float *y,long *incy,long trans_len);
extern int GLOBALMOD sger_(long *m,long *n,float *alpha,float *x,long *incx,float *y,long *incy,float *a,long *lda);
extern double GLOBALMOD snrm2_(long *n,float *sx,long *incx);
extern int GLOBALMOD srot_(long *n,float *sx,long *incx,float *sy,long *incy,float *c,float *s);
extern int GLOBALMOD srotg_(float *sa,float *sb,float *c,float *s);
extern int GLOBALMOD srotm_(long *n,float *sx,long *incx,float *sy,long *incy,float *sparam);
extern int GLOBALMOD srotmg_(float *sd1,float *sd2,float *sx1,float *sy1,float *sparam);
extern int GLOBALMOD ssbmv_(char *uplo,long *n,long *k,float *alpha,float *a,long *lda,float *x,long *incx,float *beta,float *y,long *incy,long uplo_len);
extern int GLOBALMOD sscal_(long *n,float *sa,float *sx,long *incx);
extern int GLOBALMOD sspmv_(char *uplo,long *n,float *alpha,float *ap,float *x,long *incx,float *beta,float *y,long *incy,long uplo_len);
extern int GLOBALMOD sspr_(char *uplo,long *n,float *alpha,float *x,long *incx,float *ap,long uplo_len);
extern int GLOBALMOD sspr2_(char *uplo,long *n,float *alpha,float *x,long *incx,float *y,long *incy,float *ap,long uplo_len);
extern int GLOBALMOD sswap_(long *n,float *sx,long *incx,float *sy,long *incy);
extern int GLOBALMOD ssymm_(char *side,char *uplo,long *m,long *n,float *alpha,float *a,long *lda,float *b,long *ldb,float *beta,float *c,long *ldc,long side_len,long uplo_len);
extern int GLOBALMOD ssymv_(char *uplo,long *n,float *alpha,float *a,long *lda,float *x,long *incx,float *beta,float *y,long *incy,long uplo_len);
extern int GLOBALMOD ssyr_(char *uplo,long *n,float *alpha,float *x,long *incx,float *a,long *lda,long uplo_len);
extern int GLOBALMOD ssyr2_(char *uplo,long *n,float *alpha,float *x,long *incx,float *y,long *incy,float *a,long *lda,long uplo_len);
extern int GLOBALMOD ssyr2k_(char *uplo,char *trans,long *n,long *k,float *alpha,float *a,long *lda,float *b,long *ldb,float *beta,float *c,long *ldc,long uplo_len,long trans_len);
extern int GLOBALMOD ssyrk_(char *uplo,char *trans,long *n,long *k,float *alpha,float *a,long *lda,float *beta,float *c,long *ldc,long uplo_len,long trans_len);
extern int GLOBALMOD stbmv_(char *uplo,char *trans,char *diag,long *n,long *k,float *a,long *lda,float *x,long *incx,long uplo_len,long trans_len,long diag_len);
extern int GLOBALMOD stbsv_(char *uplo,char *trans,char *diag,long *n,long *k,float *a,long *lda,float *x,long *incx,long uplo_len,long trans_len,long diag_len);
extern int GLOBALMOD stpmv_(char *uplo,char *trans,char *diag,long *n,float *ap,float *x,long *incx,long uplo_len,long trans_len,long diag_len);
extern int GLOBALMOD stpsv_(char *uplo,char *trans,char *diag,long *n,float *ap,float *x,long *incx,long uplo_len,long trans_len,long diag_len);
extern int GLOBALMOD strmm_(char *side,char *uplo,char *transa,char *diag,long *m,long *n,float *alpha,float *a,long *lda,float *b,long *ldb,long side_len,long uplo_len,long transa_len,long diag_len);
extern int GLOBALMOD strmv_(char *uplo,char *trans,char *diag,long *n,float *a,long *lda,float *x,long *incx,long uplo_len,long trans_len,long diag_len);
extern int GLOBALMOD strsm_(char *side,char *uplo,char *transa,char *diag,long *m,long *n,float *alpha,float *a,long *lda,float *b,long *ldb,long side_len,long uplo_len,long transa_len,long diag_len);
extern int GLOBALMOD strsv_(char *uplo,char *trans,char *diag,long *n,float *a,long *lda,float *x,long *incx,long uplo_len,long trans_len,long diag_len);
extern int GLOBALMOD xerbla_(char *srname,long *info,long srname_len);
extern int GLOBALMOD zaxpy_(long *n,struct *za,struct *zx,long *incx,struct *zy,long *incy); 
extern int GLOBALMOD zcopy_(long *n,struct *zx,long *incx,struct *zy,long *incy); 
extern void GLOBALMOD zdotc_(struct *ret_val,long *n,struct *zx,long *incx,struct *zy,long *incy); 
extern void GLOBALMOD zdotu_(struct *ret_val,long *n,struct *zx,long *incx,struct *zy,long *incy); 
extern int GLOBALMOD zdrot_(long *n,struct *zx,long *incx,struct *zy,long *incy,double *c,double *s); 
extern int GLOBALMOD zdscal_(long *n,double *da,struct *zx,long *incx); 
extern int GLOBALMOD zgbmv_(char *trans,long *m,long *n,long *kl,long *ku,struct *alpha,struct *a,long *lda,struct *x,long *incx,struct *beta,struct *y,long *incy,long trans_len); 
extern int GLOBALMOD zgemm_(char *transa,char *transb,long *m,long *n,long *k,struct *alpha,struct *a,long *lda,struct *b,long *ldb,struct *beta,struct *c,long *ldc,long transa_len,long transb_len); 
extern int GLOBALMOD zgemv_(char *trans,long *m,long *n,struct *alpha,struct *a,long *lda,struct *x,long *incx,struct *beta,struct *y,long *incy,long trans_len); 
extern int GLOBALMOD zgerc_(long *m,long *n,struct *alpha,struct *x,long *incx,struct *y,long *incy,struct *a,long *lda); 
extern int GLOBALMOD zgeru_(long *m,long *n,struct *alpha,struct *x,long *incx,struct *y,long *incy,struct *a,long *lda); 
extern int GLOBALMOD zhbmv_(char *uplo,long *n,long *k,struct *alpha,struct *a,long *lda,struct *x,long *incx,struct *beta,struct *y,long *incy,long uplo_len); 
extern int GLOBALMOD zhemm_(char *side,char *uplo,long *m,long *n,struct *alpha,struct *a,long *lda,struct *b,long *ldb,struct *beta,struct *c,long *ldc,long side_len,long uplo_len); 
extern int GLOBALMOD zhemv_(char *uplo,long *n,struct *alpha,struct *a,long *lda,struct *x,long *incx,struct *beta,struct *y,long *incy,long uplo_len); 
extern int GLOBALMOD zher_(char *uplo,long *n,double *alpha,struct *x,long *incx,struct *a,long *lda,long uplo_len); 
extern int GLOBALMOD zher2_(char *uplo,long *n,struct *alpha,struct *x,long *incx,struct *y,long *incy,struct *a,long *lda,long uplo_len); 
extern int GLOBALMOD zher2k_(char *uplo,char *trans,long *n,long *k,struct *alpha,struct *a,long *lda,struct *b,long *ldb,double *beta,struct *c,long *ldc,long uplo_len,long trans_len); 
extern int GLOBALMOD zherk_(char *uplo,char *trans,long *n,long *k,double *alpha,struct *a,long *lda,double *beta,struct *c,long *ldc,long uplo_len,long trans_len); 
extern int GLOBALMOD zhpmv_(char *uplo,long *n,struct *alpha,struct *ap,struct *x,long *incx,struct *beta,struct *y,long *incy,long uplo_len); 
extern int GLOBALMOD zhpr_(char *uplo,long *n,double *alpha,struct *x,long *incx,struct *ap,long uplo_len); 
extern int GLOBALMOD zhpr2_(char *uplo,long *n,struct *alpha,struct *x,long *incx,struct *y,long *incy,struct *ap,long uplo_len); 
extern int GLOBALMOD zscal_(long *n,struct *za,struct *zx,long *incx); 
extern int GLOBALMOD zswap_(long *n,struct *zx,long *incx,struct *zy,long *incy); 
extern int GLOBALMOD zsymm_(char *side,char *uplo,long *m,long *n,struct *alpha,struct *a,long *lda,struct *b,long *ldb,struct *beta,struct *c,long *ldc,long side_len,long uplo_len); 
extern int GLOBALMOD zsyr2k_(char *uplo,char *trans,long *n,long *k,struct *alpha,struct *a,long *lda,struct *b,long *ldb,struct *beta,struct *c,long *ldc,long uplo_len,long trans_len); 
extern int GLOBALMOD zsyrk_(char *uplo,char *trans,long *n,long *k,struct *alpha,struct *a,long *lda,struct *beta,struct *c,long *ldc,long uplo_len,long trans_len); 
extern int GLOBALMOD ztbmv_(char *uplo,char *trans,char *diag,long *n,long *k,struct *a,long *lda,struct *x,long *incx,long uplo_len,long trans_len,long diag_len); 
extern int GLOBALMOD ztbsv_(char *uplo,char *trans,char *diag,long *n,long *k,struct *a,long *lda,struct *x,long *incx,long uplo_len,long trans_len,long diag_len); 
extern int GLOBALMOD ztpmv_(char *uplo,char *trans,char *diag,long *n,struct *ap,struct *x,long *incx,long uplo_len,long trans_len,long diag_len); 
extern int GLOBALMOD ztpsv_(char *uplo,char *trans,char *diag,long *n,struct *ap,struct *x,long *incx,long uplo_len,long trans_len,long diag_len); 
extern int GLOBALMOD ztrmm_(char *side,char *uplo,char *transa,char *diag,long *m,long *n,struct *alpha,struct *a,long *lda,struct *b,long *ldb,long side_len,long uplo_len,long transa_len,long diag_len); 
extern int GLOBALMOD ztrmv_(char *uplo,char *trans,char *diag,long *n,struct *a,long *lda,struct *x,long *incx,long uplo_len,long trans_len,long diag_len); 
extern int GLOBALMOD ztrsm_(char *side,char *uplo,char *transa,char *diag,long *m,long *n,struct *alpha,struct *a,long *lda,struct *b,long *ldb,long side_len,long uplo_len,long transa_len,long diag_len); 
extern int GLOBALMOD ztrsv_(char *uplo,char *trans,char *diag,long *n,struct *a,long *lda,struct *x,long *incx,long uplo_len,long trans_len,long diag_len); 
